### ISSUE TITLE
How to write Iterator over Node ?

### ISSUE THREAD

**Issue by davnav** [mathiversen/html-parser#6]
I would like to iterate over the Children Vec node and get each tag associated with it. How do I write that ? Please advise 
I started with below . But hard to traverse through the children. Is it possible for me write a Iterator implementation for Node ?
[parse and createelement](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0d2edfbfe01d80fc52309417e842112e)

**Comment by mathiversen** [comment]
Hi, thanks for opening this issue! I didn't implement an iterator since the data structure with nested nodes kind of complicates things a bit. However i took some time this weekend to look into it and added support for into_iter on the Node struct. It should be fairly simple now to loop over all nodes in the three and basically just sort out the ones you like. I've added an example in the repo where i get all of the anchor-links, in short:
```rust    
    let dom = Dom::parse(html)?;
    let iter = dom.children.get(0).unwrap().into_iter();
```
Hope it helps!

**Comment by jkelleyrtp** [comment]
Just want to say that I'm super impressed by the bit of code you wrote for your iterator. 

Because I ended up writing nearly exactly the same for my iterator.  Over 8 months later. Without looking or knowing about your version. With nearly the same variable names and structure. Kudos!
